### ISSUE TITLE
can't load module as libary in a node app 

### ISSUE THREAD

**Issue by msudol** [janispritzkau/mc-server-status#1]
Getting the following bug on load of my node app implementing mc-server-status.

```
/mcproto/lib/packet.js:57
        return (first << 32n) + last;
                         ^^
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

my Node version is 9.11.2

**Comment by janispritzkau** [comment]
Sorry, I'm using BigInt's, more specifically the BigInt notation, in one of the dependencies. BigInts are only supported in Node 10+. I would expect most people to use Node 10 or higher, as the latest LTS version is 12.

**Comment by msudol** [comment]
Was just trying to implement on some legacy projects I had laying around, updated node and it's all good.
