### ISSUE TITLE
TypeError: host.includes is not a function

### ISSUE THREAD

**Issue by nomoemptypointer** [janispritzkau/mc-server-status#4]
Well i tried to use this package for my project i am making in Discord.js and im always running into this problem, even using port, i have not tried updating node.

```
F:\minecraftbot\node_modules\mcproto\lib\client.js:27
        const isIp = host.includes(":") || /^([0-9]+\.){3}[0-9]+$/.test(host);
                          ^

TypeError: host.includes is not a function

```
My code:
```
    if(message.content.startsWith(prefix + 'stat')) {
        const content = message.content.split(' ');
        const args = content.slice(1);
        const input = parseInt(args[0]);
        const status = await getStatus(input)
        message.channel.send(status);
    }
```

**Comment by janispritzkau** [comment]
I think you are not using the function correctly.

The type signature of the function is: `(host: string, port?: number | null, options?: StatusOptions) => Promise<Status>`. 

It looks like you are passing an integer as the first argument.

**Comment by nomoemptypointer** [comment]
Yeeeah, that might be issue, i totally forgot about it, ill let know if it works with an different function.

**Comment by nomoemptypointer** [comment]
Yep, works, closing the issue.
